## Lab Assignment 10: <br>
### Student Name: Paras Rupani
### Student ID:   8961758

This assignment targets to assure that the students understood basic IR concepts.<br>

**Part 1: Implementing an IR System (10/16)**<br>

Consider a collection of 1000 documents and a set of 10 queries. Implement an IR system based on the Vector Space Model (VSM) using TF-IDF weighting.<br>

Dataset:<br>

- 1000 documents (text content for each document)
- 10 sample queries <br>
IR System:<br>

Implement TF-IDF calculation for document-term matrix construction. <br>
Develop a cosine similarity-based retrieval system to rank documents for each query. <br>
Rank the top 10 documents for each query using the IR system. <br>
Evaluation: <br>

Compute Precision at k (P@k) for k=5, k=6, and k=10 for each query.<br>
Calculate Mean Average Precision (MAP) across all queries. <br>
Calculate the Mean Reciprocal Rank (MRR) across all queries.(3) <br><br>
**Part 2: Assessing Inter-Annotator Agreement (6/16)**<br>

Given the relevance assessments by three different annotators for a set of documents:<br>

Annotator 1,2 and 3 relevance assessments<br>

You are expected to: <br>

Compute pairwise Cohen's Kappa values for the annotators' relevance assessments.<br>
Discuss the observed agreement levels among annotators.<br>
Explain how to improve the kappa value if we are not satisfied with the kappa.<br>
Hint: Check Kappa Measure Last Slide Week 11


----------------------------------------------------------------------------------------
- Part 1

In [16]:
documents = [
    "Machine learning is transforming various industries.",
    "Natural language processing helps in text analysis.",
    "AI algorithms can improve decision-making processes.",
    "Data science involves extracting insights from data.",
    "Robotics is a field combining hardware and software.",
    "Deep learning models require large amounts of data.",
    "Blockchain technology secures digital transactions.",
    "Cloud computing offers scalable computing power.",
    "Virtual reality provides immersive experiences.",
    "Augmented reality enhances real-world environments.",
    "Internet of Things connects devices for data exchange.",
    "Biometric authentication ensures secure access.",
    "Quantum computing promises faster computations.",
    "Cybersecurity protects against digital threats.",
    "Ethical considerations in AI development are crucial.",
    "Healthcare benefits from AI-driven diagnostics.",
    "E-commerce relies on personalized recommendation systems.",
    "Autonomous vehicles revolutionize transportation.",
    "Smart cities utilize IoT for efficient operations.",
    "Social media analysis aids in understanding trends.",
    "Predictive analytics anticipates future outcomes.",
    "Remote work trends increase reliance on digital tools.",
    "Energy efficiency through smart grids is vital.",
    "Fintech innovations reshape financial services.",
    "Data privacy concerns arise in the era of big data.",
    "Artificial general intelligence remains a challenge.",
    "Human-computer interaction shapes user experiences.",
    "Big data analytics drives informed decision-making.",
    "Climate change predictions benefit from AI models.",
    "Bioinformatics applies computational techniques to biology.",
    "Robotic process automation streamlines workflows.",
    "Industry 4.0 integrates AI with manufacturing.",
    "Sentiment analysis detects emotions in text data.",
    "Reinforcement learning powers autonomous agents.",
    "Data visualization simplifies complex information.",
    "Edge computing reduces latency in data processing.",
    "Smart farming optimizes agricultural practices.",
    "AI in education enhances personalized learning.",
    "Natural disaster predictions leverage machine learning.",
    "Media recommendation systems personalize content.",
    "Speech recognition enables hands-free interactions.",
    "Genetic algorithms mimic natural selection.",
    "Neural networks simulate the human brain.",
    "Behavioral analytics uncovers patterns in behavior.",
    "Spatial analysis benefits from geospatial data.",
    "Explainable AI improves transparency in models.",
    "AI ethics guide responsible technology development.",
    "Prescriptive analytics offers actionable insights.",
    "Supply chain optimization employs predictive models.",
    "Emotion AI detects emotions in facial expressions.",
    "Distributed ledger technology ensures secure transactions.",
    "Biological data analysis aids in medical research.",
    "Smart grid technology enhances energy distribution.",
    "AI-powered chatbots automate customer support.",
    "Machine translation breaks language barriers.",
    "Personalized medicine tailors treatments to individuals.",
    "Data-driven marketing optimizes customer engagement.",
    "Smart home devices enhance living experiences.",
    "Time series forecasting predicts future trends.",
    "AI-driven creativity challenges human capabilities.",
    "Intelligent document processing automates data extraction.",
    "Graph analytics explores relationships in networks.",
    "Adversarial attacks pose challenges to AI security.",
    "Predictive maintenance minimizes equipment downtime.",
    "Spatial reasoning enhances AI navigation systems.",
    "Privacy-preserving techniques protect sensitive data.",
    "Automated decision-making raises ethical concerns.",
    "Behavioral biometrics verifies user identities.",
    "Explainable recommendations increase user trust.",
    "Quantum machine learning explores quantum states.",
    "Internet censorship detection uses AI techniques.",
    "Smart wearables monitor health and fitness.",
    "Intelligent tutoring systems adapt to student needs.",
    "Graph neural networks model complex relationships.",
    "AI in sports analytics improves performance analysis.",
    "Facial recognition technology raises privacy debates.",
    "Digital twin technology replicates physical systems.",
    "Emotion detection in video content aids analysis.",
    "Neuromorphic computing mimics brain structure.",
    "Robotic surgery enhances precision in operations.",
    "AI-powered language translation assists global communication.",
    "Automated content moderation filters online content.",
    "Network anomaly detection identifies security threats.",
    "Predictive policing uses data to prevent crime.",
    "Quantum cryptography ensures secure communications.",
    "AI-generated art challenges traditional creativity.",
    "Ethical considerations in autonomous vehicles are debated.",
    "Adaptive learning systems personalize educational content.",
    "Biomedical image analysis aids in disease diagnosis.",
    "Explainable computer vision interprets image features.",
    "AI-driven personalization enhances user experiences.",
    "Conversational AI improves human-like interactions.",
    "Federated learning protects individual data privacy.",
    "Human-centered AI design prioritizes user needs.",
    "Quantum annealing solves optimization problems.",
    "Behavior-based authentication enhances security.",
    "AI in music composition transforms creative processes.",
    "Semantic search improves information retrieval.",
    "Recommender systems optimize user preferences.",
    "Information Retrieval systems are outdated without neural networks"
]
print(len(documents))

100


In [17]:
queries = [
    "What are the impacts of AI on healthcare?",
    "How does machine learning improve financial services?",
    "What is the role of AI in autonomous vehicles?",
    "Explain the applications of natural language processing.",
    "How does robotics benefit from AI integration?",
    "What are the challenges in implementing AI in education?",
    "How does data science contribute to climate change predictions?",
    "What are the ethical considerations in AI development?",
    "Explain the significance of AI in smart cities.",
    "How does AI enhance cybersecurity measures?"
]
print(len(queries))

10


In [18]:
ground_truth =[[3, 74, 38, 92, 71, 72, 98, 48, 18, 100], 
                [12, 26, 52, 54, 21, 63, 64, 45, 14, 83],
                [58, 77, 62, 31, 6, 61, 36, 96, 85, 18], 
                [99, 62, 98, 34, 63, 79, 43, 31, 3, 16],
                [8, 88, 73, 82, 37, 25, 34, 87, 66, 58], 
                [90, 40, 84, 64, 34, 2, 73, 23, 59, 89],
                [80, 10, 86, 21, 68, 37, 83, 57, 6, 98],
                [22, 3, 2, 44, 56, 80, 50, 63, 87, 13],
                [1, 18, 22, 44, 99, 72, 24, 95, 10, 87],
                [31, 10, 56, 50, 75, 4, 18, 85, 84, 74]
                           ]
print(len(ground_truth))


10


In [19]:
## TODO: Implement your solution for part 1

import numpy as np, pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics.pairwise import cosine_similarity

In [20]:
# Initialize a TfidfVectorizer instance for vectorizing queries and documents
vectorizer = TfidfVectorizer()

# Fit and transform the documents into TF-IDF representation
tfidf_documents = vectorizer.fit_transform(documents)

# Transform the queries into TF-IDF representation
tfidf_queries = vectorizer.transform(queries)

# Calculate cosine similarity between queries and documents
cosine_sim = cosine_similarity(tfidf_queries, tfidf_documents)

# Retrieve top 10 documents for each query based on cosine similarity
lab_10_query = [np.argsort(cosine_similarity_row)[-10:][::-1] for cosine_similarity_row in cosine_sim]

lab_10_query

[array([15, 24, 14, 42, 16, 86, 21, 99,  5, 10]),
 array([23, 38,  0, 69,  2, 54, 37, 33, 92, 87]),
 array([17, 86, 24, 42, 33,  0, 37, 22,  5, 45]),
 array([ 1, 24, 42, 54, 41, 38, 60, 35, 80,  5]),
 array([28, 15,  4, 44,  3, 37, 45, 90, 64, 59]),
 array([37, 14, 86, 24, 59, 85, 45, 62, 74, 42]),
 array([28,  3, 83, 38, 29, 55, 62, 72, 24, 34]),
 array([14, 86, 46, 24, 42, 66, 37, 99, 45, 74]),
 array([24, 18, 42, 37,  5, 45, 10, 74, 36, 52]),
 array([13, 57, 37, 45, 90, 64, 59, 74, 31, 91])]

In [21]:
# Iterate over each query and its index using enumerate
for i, doc_queries in enumerate(queries):
    print("Query:", doc_queries)    
    for rank, doc_index in enumerate(lab_10_query[i]):    
        print(f'Rank-{rank+1}: Index:{[doc_index]}\t{documents[doc_index]}')
    
    print("\n------------------------------------------------------------------------------------------------\n")


Query: What are the impacts of AI on healthcare?
Rank-1: Index:[15]	Healthcare benefits from AI-driven diagnostics.
Rank-2: Index:[24]	Data privacy concerns arise in the era of big data.
Rank-3: Index:[14]	Ethical considerations in AI development are crucial.
Rank-4: Index:[42]	Neural networks simulate the human brain.
Rank-5: Index:[16]	E-commerce relies on personalized recommendation systems.
Rank-6: Index:[86]	Ethical considerations in autonomous vehicles are debated.
Rank-7: Index:[21]	Remote work trends increase reliance on digital tools.
Rank-8: Index:[99]	Information Retrieval systems are outdated without neural networks
Rank-9: Index:[5]	Deep learning models require large amounts of data.
Rank-10: Index:[10]	Internet of Things connects devices for data exchange.

------------------------------------------------------------------------------------------------

Query: How does machine learning improve financial services?
Rank-1: Index:[23]	Fintech innovations reshape financial se

In [22]:
# Firstly, creating a function to calculate Precision at k
def precision_at_k(document_retrieved, ground_truth_docs, k):
    """
    Calculate Precision at k for retrieved documents.

    Args:
        document_retrieved (list): List of retrieved document IDs.
        ground_truth_docs (set): Set of ground truth document IDs.
        k (int): Value of k for precision@k.

    Returns:
        float: Precision at k.
    """
    
    # Convert ground_truth_docs to a set for faster intersection operation
    document_relevant = set(ground_truth_docs)
    documents_retrieved_at_k = set(document_retrieved[:k]) # top k retrieved documents
    true_positives = len(document_relevant.intersection(documents_retrieved_at_k)) # number of true positives
    
    print(f"Retrieved Document at {k} \n {documents_retrieved_at_k}")

    return true_positives / k


In [23]:
# Calculating precision at k and mapping
precisions = {k: [] for k in [5, 6, 10]}

# Processing each query and its retrieved documents
for query, document_retrieved in enumerate(lab_10_query):
    ground_truth_docs = ground_truth[query] # Retriving Ground Truth
    for k in precisions:
        # Append precision at k for the current query to the list
        precisions[k].append(precision_at_k(document_retrieved, ground_truth_docs, k))


Retrieved Document at 5 
 {42, 14, 15, 16, 24}
Retrieved Document at 6 
 {42, 14, 15, 16, 86, 24}
Retrieved Document at 10 
 {99, 5, 42, 10, 14, 15, 16, 21, 86, 24}
Retrieved Document at 5 
 {0, 2, 69, 38, 23}
Retrieved Document at 6 
 {0, 2, 69, 38, 54, 23}
Retrieved Document at 10 
 {0, 33, 2, 69, 38, 37, 54, 23, 87, 92}
Retrieved Document at 5 
 {33, 42, 17, 86, 24}
Retrieved Document at 6 
 {0, 33, 42, 17, 86, 24}
Retrieved Document at 10 
 {0, 33, 37, 5, 42, 45, 17, 86, 22, 24}
Retrieved Document at 5 
 {1, 41, 42, 54, 24}
Retrieved Document at 6 
 {1, 38, 41, 42, 54, 24}
Retrieved Document at 10 
 {1, 35, 5, 38, 41, 42, 80, 54, 24, 60}
Retrieved Document at 5 
 {3, 4, 44, 15, 28}
Retrieved Document at 6 
 {3, 4, 37, 44, 15, 28}
Retrieved Document at 10 
 {64, 3, 4, 37, 44, 45, 15, 90, 59, 28}
Retrieved Document at 5 
 {37, 14, 86, 24, 59}
Retrieved Document at 6 
 {37, 14, 85, 86, 24, 59}
Retrieved Document at 10 
 {37, 74, 42, 45, 14, 85, 86, 24, 59, 62}
Retrieved Document at 5 

In [24]:
# Lastly, creating another function to calculate MRR
def MRR(document_retrieved_list, ground_truth_list):
    """
    Calculate Mean Reciprocal Rank (MRR) for a list of queries.

    Args:
        document_retrieved_list (list): List of lists, each containing retrieved document IDs for a query.
        ground_truth_list (list): List of sets, each containing ground truth document IDs for a query.

    Returns:
        float: Mean Reciprocal Rank (MRR).
    """

    mrr = 0

    # Interating Over Retrieved Documents
    for document_retrieved, ground_truth_docs in zip(document_retrieved_list, ground_truth_list): 
        
        # Finding Rank of First Relevant Document
        for rank, document_id in enumerate(document_retrieved, start=1): 
            if document_id in ground_truth_docs: # Checking Relevancy
                mrr += 1 / rank
                break
    # Calculating Mean Reciprocal Rank
    return mrr / len(document_retrieved_list)


In [25]:
# Calculating Mean Reciprocal Rank using the function
mrr_score = MRR(lab_10_query, ground_truth)


for k, values in precisions.items():
    # Round each value in the list to 2 decimal places
    k_values = [round(value, 2) for value in values]
    print(f"Precision at k={k}: {k_values}")
    
    # MAP score for the current k
    map_score_k = sum(values) / len(values)
    # MAP score for the current k
    print(f"Mean Average Precision (MAP) of k={k}: {map_score_k} \n")
    
    # Overall Mean MAP score 
    map_score = np.mean(map_score_k)

# Overall MAP score
print("Mean Average Precision (MAP):", map_score)

# MRR Score
print("Mean Reciprocal Rank (MRR):", round(mrr_score, 2))


Precision at k=5: [0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.2, 0.0, 0.4, 0.0]
Mean Average Precision (MAP) of k=5: 0.08 

Precision at k=6: [0.0, 0.17, 0.0, 0.0, 0.17, 0.17, 0.17, 0.0, 0.33, 0.0]
Mean Average Precision (MAP) of k=6: 0.1 

Precision at k=10: [0.0, 0.1, 0.0, 0.0, 0.1, 0.1, 0.1, 0.0, 0.3, 0.2]
Mean Average Precision (MAP) of k=10: 0.09 

Mean Average Precision (MAP): 0.09
Mean Reciprocal Rank (MRR): 0.2


-------------------------------------------------------------------
**Part 2: Assessing Inter-Annotator Agreement (6/16)**<br>

Given the relevance assessments by three different annotators for a set of documents:<br>

Annotator 1,2 and 3 relevance assessments<br>

You are expected to: <br>

Compute pairwise Cohen's Kappa values for the annotators' relevance assessments.<br>
Discuss the observed agreement levels among annotators.<br>
Explain how to improve the kappa value if we are not satisfied with the kappa.<br>

In [26]:
# 0 is not relevant, 1 is relevant
annotator1_relevance = [1, 0, 1, 0, 1, 1, 0, 0, 1, 0]  
annotator2_relevance = [1, 1, 1, 0, 1, 0, 0, 1, 1, 1]  
annotator3_relevance = [1, 0, 0, 0, 1, 0, 0, 1, 1, 0]  

In [27]:
## TODO: Implement your solution for part 2

# Calculating cohen_kappa_score() for annotator 1,2 and 3
kappa_1_2 = cohen_kappa_score(annotator1_relevance, annotator2_relevance)
kappa_2_3 = cohen_kappa_score(annotator2_relevance, annotator3_relevance)
kappa_1_3 = cohen_kappa_score(annotator1_relevance, annotator3_relevance)

# Dictionary holding the data
data = {
    'Annotator Pairs': ['1 and 2', '2 and 3', '1 and 3'],
    'Cohen\'s Kappa Score': [round(kappa_1_2, 2), round(kappa_2_3, 2), round(kappa_1_3, 2)]
}

for pair, kappa_score in zip(data['Annotator Pairs'], data['Cohen\'s Kappa Score']):
    print(f"Kappa between Pairs {pair}: {kappa_score}")

df = pd.DataFrame(data)
df

Kappa between Pairs 1 and 2: 0.2
Kappa between Pairs 2 and 3: 0.44
Kappa between Pairs 1 and 3: 0.4


Annotator Pairs  Cohen's Kappa Score
0         1 and 2                 0.20
1         2 and 3                 0.44
2         1 and 3                 0.40